sudo: required
services:
  - docker

os: linux
dist: xenial
language: minimal

before_install:
  - >-
    declare -g -A TOOLSET_REPOS=(
      [common_toolset]=sandbox.galaxyproject.org
      [test.galaxyproject.org]=test.galaxyproject.org
    )
  - >-
    declare -g -A REPO_USERS=(
      [sandbox.galaxyproject.org]=sandbox
      [test.galaxyproject.org]=g2test
    )
  - >-
    declare -g -A REPO_STRATUM0S=(
      [sandbox.galaxyproject.org]=cvmfs0-psu0.galaxyproject.org
      [test.galaxyproject.org]=cvmfs0-tacc0.galaxyproject.org
    )
  - >-
    declare -g -A CONDA_PATHS=(
      [sandbox.galaxyproject.org]=/cvmfs/sandbox.galaxyproject.org/dependencies/conda
      [test.galaxyproject.org]=/cvmfs/test.galaxyproject.org/deps/_conda
    )
  - echo 'Detecting changes to tool files...'
  - git diff --quiet "$TRAVIS_COMMIT_RANGE" --; GIT_DIFF_EXIT_CODE=$?
  - |
    if [ "$GIT_DIFF_EXIT_CODE" -gt 1 ]; then
        git remote set-branches --add origin master
        git fetch
        TRAVIS_COMMIT_RANGE=origin/master...
    fi
  - echo "\$TRAVIS_COMMIT_RANGE is $TRAVIS_COMMIT_RANGE"
  - echo "Change detection limited to toolset directories:"; for d in "${!TOOLSET_REPOS[@]}"; do echo "${d}/"; done
  - |
    TOOLSET= ;
    while read op path; do
        if [ -n "$TOOLSET" -a "$TOOLSET" != "${path%%/*}" ]; then
            echo "ERROR: Changes to tools in multiple toolsets found, terminating: ${TOOLSET} != ${path%%/*}"
            travis_terminate 1
        elif [ -z "$TOOLSET" ]; then
            TOOLSET="${path%%/*}"
        fi
        case "${path##*.}" in
            lock)
                ;;
            *)
                continue
                ;;
        esac
        case "$op" in
            A|M)
                echo "$op $path"
                TOOL_YAMLS+=("${path}")
                ;;
        esac
    done < <(git diff --color=never --name-status "$TRAVIS_COMMIT_RANGE" -- $(for d in "${!TOOLSET_REPOS[@]}"; do echo "${d}/"; done))
  - set | grep '^TOOL'
  - |
    if [ ${#TOOL_YAMLS[@]} -eq 0 ]; then
        echo 'No tool changes, terminating'
        travis_terminate 0
    fi
  - REPO="${TOOLSET_REPOS[$TOOLSET]}"
  - |
    if [ -n "$REPO" ]; then
        echo "Setting up CVMFS for repo ${REPO}"
    else
        echo "ERROR: No repo defined for toolset $TOOLSET, set one in \$TOOLSET_REPOS"
        travis_terminate 1
    fi
  - sudo groupadd --gid 1450 cvmfs
  - sudo useradd --uid 1450 --gid 1450 cvmfs
  - sudo mkdir /lower /upper /work /cvmfs /cvmfs/${REPO}
  - curl -O https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
  - sudo dpkg -i cvmfs-release-latest_all.deb
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y cvmfs
  - sudo cp .ci/default.local /etc/cvmfs
  - sudo cp .ci/*.pub /etc/cvmfs/keys
  - sudo mount -t cvmfs "$REPO" "/lower"
  - sudo mount -t overlay overlay -o lowerdir=/lower,upperdir=/upper,workdir=/work "/cvmfs/${REPO}"

install:
  - sudo pip install ephemeris planemo
  - >-
    docker run -d -p 8080:80 --name=galaxy
    -e GALAXY_CONFIG_INSTALL_DATABASE_CONNECTION=sqlite:////cvmfs/${REPO}/config/install.sqlite
    -e GALAXY_CONFIG_TOOL_CONFIG_FILE=/cvmfs/${REPO}/config/shed_tool_conf.xml
    -e GALAXY_CONFIG_MASTER_API_KEY=deadbeef
    -e GALAXY_CONFIG_CONDA_PREFIX=${CONDA_PATHS[$REPO]}
    -e GALAXY_HANDLER_NUMPROCS=0
    -e CONDARC=${CONDA_PATHS[$REPO]}rc
    -v /cvmfs/${REPO}:/cvmfs/${REPO}
    -v $(pwd)/.ci/job_conf.xml:/job_conf.xml
    -v $(pwd)/.ci/nginx.conf:/etc/nginx/nginx.conf
    -e GALAXY_CONFIG_JOB_CONFIG_FILE=/job_conf.xml
    bgruening/galaxy-stable
  - |
    galaxy-wait -v --timeout 120 || {
        echo "#### TIMED OUT WAITING FOR GALAXY ####";
        for f in /var/log/nginx/error.log /home/galaxy/logs/uwsgi.log; do
            echo "#### CONTENTS OF ${f}:";
            docker exec galaxy cat $f;
        done;
        echo "#### RESPONSE FROM http://localhost:8080:";
        curl http://localhost:8080;
        echo "#### TERMINATING BUILD";
        travis_terminate 1;
    }

script:
  - |
    for tool_yaml in "${TOOL_YAMLS[@]}"; do
        shed-tools install -v -a deadbeef -t "$tool_yaml" || {
            echo "#### TOOL INSTALL ERROR ####";
            for f in /var/log/nginx/error.log /var/log/nginx/access.log /home/galaxy/logs/uwsgi.log; do
                echo "#### TAIL OF ${f}:";
                docker exec galaxy tail -500 $f;
            done;
            echo "#### TERMINATING BUILD";
            travis_terminate 1;
        }
        #shed-tools install -v -a deadbeef -t "$tool_yaml" --test --test_json "${tool_yaml##*/}"-test.json || {
        #    # TODO: test here if test failures should be ignored (but we can't separate test failures from install
        #    # failures at the moment) and also we can't easily get the job stderr
        #    [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ] || {
        #        echo "#### TOOL INSTALL/TEST FAILED ####";
        #        echo "#### CONTENTS OF /home/galaxy/logs/uwsgi.log:";
        #       docker exec galaxy cat /home/galaxy/logs/uwsgi.log;
        #       echo "#### TERMINATING BUILD";
        #       travis_terminate 1;
        #    };
        #}
    done
  #- |
  #  for tool_yaml in "${TOOL_YAMLS[@]}"; do
  #      planemo test_reports --test_output_text tests.txt "${tool_yaml##*/}"-test.json && cat tests.txt
  #  done

after_success:
  # TODO: uncomment following line
  #- '[ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "master" ] && travis_terminate 0 || true'
  - openssl aes-256-cbc -K $encrypted_0ffba610202a_key -iv $encrypted_0ffba610202a_iv -in .ci/deploy_key.pem.enc -out .ci/deploy_key.pem -d
  - cp -p .ci/known_hosts $HOME/.ssh/known_hosts
  - eval "$(ssh-agent -s)"
  - chmod 600 .ci/deploy_key.pem
  - ssh-add .ci/deploy_key.pem
  - sudo find /upper -perm -u+r -not -perm -o+r -not -type l -print0 | sudo xargs -0 --no-run-if-empty chmod go+r
  - sudo find /upper -perm -u+rx -not -perm -o+rx -not -type l -print0 | sudo xargs -0 --no-run-if-empty chmod go+rx
  - sudo ${CONDA_PATHS[$REPO]}/bin/conda clean --tarballs --yes
  - REPO_USER=${REPO_USERS[$REPO]}
  - REPO_STRATUM0=${REPO_STRATUM0S[$REPO]}
  - echo "Pushing changes to repo ${REPO} on CVMFS Stratum 0 ${REPO_STRATUM0} as user ${REPO_USER}"
  - ssh ${REPO_USER}@${REPO_STRATUM0} cvmfs_server transaction ${REPO}
  - |
    rsync -av /upper/ ${REPO_USER}@${REPO_STRATUM0}:/cvmfs/${REPO} || {
        echo "#### RSYNC FAILED, ABORTING TRANSACTION";
        ssh ${REPO_USER}@${REPO_STRATUM0} cvmfs_server abort -f ${REPO};
        travis_terminate 1;
    }
  - ssh ${REPO_USER}@${REPO_STRATUM0} "cvmfs_server publish -m 'Automated tool install for commit $TRAVIS_COMMIT' ${REPO}"
  #- ssh ${REPO_USER}@${REPO_STRATUM0} "cvmfs_server abort -f ${REPO}"
